<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ0Tr1MR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ0Tr1MR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ0Tr1MR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ0Tr1MR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ0Tr1MR\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z0Tr1MR',
    'container.build_id' => '6bdc8280',
    'container.build_time' => 1706157706,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ0Tr1MR');
